# Generated by Django 6.0.4 on 2026-04-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_last_four',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата картой'), ('cash', 'Оплата при получении')], default='cash', max_length=20),
        ),
    ]
