# Generated by Django 6.0.4 on 2026-06-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_levelup_gamestore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение игры', 'verbose_name_plural': 'Изображения игр'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'platform', 'edition'], 'verbose_name': 'Вариант игры', 'verbose_name_plural': 'Варианты игр'},
        ),
    ]
